0,0,946685561,985,26,31,358,0,4208,0,4.79
0,0,946685564,994,26,31,358,0,4208,0,4.93
0,0,946685567,995,26,31,357,0,4208,0,4.86
0,0,946685570,1225,26,31,357,0,4208,0,4.880001
0,0,946685573,1248,26,32,358,0,4208,0,5.110001
0,0,946685576,1247,26,32,358,0,4208,0,5.0
0,0,946685579,1248,26,32,359,0,4208,0,4.95
0,0,946685582,1244,26,32,358,0,4208,0,5.04
0,0,946685585,1241,26,32,357,0,4208,0,4.960001
0,0,946685588,1238,26,32,358,0,4208,0,5.05
---------------------
34 2 231
---------------------
32 105 77
---------------------
13 98 65
---------------------
32 127 40
---------------------
22 0 14
0,0,946685591,1225,0,0,359,0,4208,0,5.02
0,0,946685594,1213,26,31,358,0,4208,0,5.05
0,0,946685597,1134,26,31,358,0,4208,0,4.900001
0,0,946685600,1104,26,31,358,0,4208,0,4.91
0,0,946685603,1107,26,31,358,0,4208,0,4.98
0,0,946685606,1062,26,31,358,0,4208,0,5.24
0,0,946685609,1043,26,31,359,0,4208,0,4.93
0,0,946685612,1024,26,31,358,0,4208,0,4.960001
0,0,946685615,1017,26,31,358,0,4208,0,5.12
0,0,946685618,1009,26,31,358,0,4208,0,5.130001
0,0,946685621,996,26,31,358,0,4208,0,5.29
0,0,946685624,990,26,31,358,0,4208,0,4.86
0,0,946685627,987,26,31,359,0,4208,0,5.08
0,0,946685630,983,26,31,358,0,4208,0,4.920001
0,0,946685633,979,26,31,358,0,4208,0,5.04
0,0,946685636,978,26,31,358,0,4208,0,5.05
0,0,946685639,977,26,31,358,0,4208,0,4.87
0,0,946685642,972,26,31,359,0,4208,0,5.01
0,0,946685645,973,26,31,358,0,4208,0,5.08
0,0,946685648,973,26,31,358,0,4208,0,5.0
0,0,946685651,974,26,31,358,0,4208,0,4.87
0,0,946685654,974,26,31,358,0,4208,0,4.940001
0,0,946685417,969,26,31,358,0,4208,0,4.95
Traceback (most recent call last):
  File "/flash/main.py", line 119, in <module>
  File "/flash/fram.py", line 254, in emergency_storage
ValueError: bytes value out of range
MicroPython v1.12-1556-gcc82fa9 on 2021-06-22; XBee3 DigiMesh 2.4 with EFR32MG
Type "help()" for more information.
>>> 
